 
export const languagesText = {
		en: {
			dayNames: ['Sunday', 'Monday', 'Tuesday',
				'Wednesday', 'Thursday', 'Friday', 'Saturday',
			],
			monthNames: ['January', 'February', 'March', 'April', 'May', 'June',
				'July', 'August', 'September', 'October', 'November', 'December',
			],
			temperature: '{{value}}',
			feelsLike: 'Feels like: {{value}}',
			wind: 'Wind: {{value}} m/s',
			humidity: 'Humidity: {{value}}%',
			longitude: 'Longitude: {{value}}',
			latitude: 'Latitude: {{value}}',
			overcast: '{{value}}',
			btnBackground: 'Background',
			btnSearch: 'Search',
			searchCity: 'Search city',
		},
		ru: {
			dayNames: ['Воскресенье', 'Понедельник', 'Вторник',
				'Среда', 'Четверг', 'Пятница', 'Суббота',
			],
			monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
				'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь',
			],
			temperature: '{{value}}',
			feelsLike: 'Ощущение: {{value}}',
			wind: 'Ветер: {{value}} м/с',
			humidity: 'Влажность: {{value}}',
			longitude: 'Долгота: {{value}}',
			latitude: 'Широта: {{value}}',
			overcast: '{{value}}',
			btnBackground: 'Фон',
			btnSearch: 'Поиск',
			searchCity: 'Поиск города',
		},
	};
